steps:
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: [ 'deploy', '--project', '$PROJECT_ID']
  secretEnv: ['FIREBASE_TOKEN']
secrets:
- kmsKeyName: projects/$PROJECT_ID/locations/global/keyRings/$_KEYRING/cryptoKeys/$_KEY
  secretEnv:
    FIREBASE_TOKEN: $_FIREBASE_TOKEN