steps:
- name: 'gcr.io/cloud-builders/npm'
  id: install
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  id: build
  waitFor:
  - install
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo $_ENV
    [[ "$_ENV" == "production" ]] && npm run build-stg && echo "Deploying on production..." 
    [[ "$_ENV" == "staging" ]] && npm run build-stg && echo "Deploying on staging..."  
- name: 'gcr.io/$PROJECT_ID/firebase'
  waitFor:
  - build
  args: [ 'deploy', '--project', '$PROJECT_ID', '-P', '$_ENV']
  secretEnv: ['FIREBASE_TOKEN']
secrets:
- kmsKeyName: projects/nowyouvote-com/locations/global/keyRings/KEYRING_NOWYOUVOTE/cryptoKeys/KEY_NOWYOUVOTE
  secretEnv:
    FIREBASE_TOKEN: CiQAe+tVl8bbbbCE+SAzkCYQAmr2jUlH+yRoEsdJph2/4lOo604SVgDQwb7wPaSwisZjDkLgQQLklmOBADMg3apH97/tEaNoHrXXHsPAlW71wwsxg8sGIp8Ty29dnHuje7XBJaKTNoIfHpco7Bk2uER6eu9DUpAzbUvineQ4